# Generated by Django 5.2.7 on 2025-11-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_company_userprofile_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='jobrole',
        ),
    ]
