# Generated by Django 5.2.7 on 2025-10-11 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('category_img', models.ImageField(upload_to='photos/%Y/%x/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='product.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img1',
            field=models.ImageField(default='product.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img2',
            field=models.ImageField(default='product.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('New', 'New'), ('Sale', 'Sale'), ('Featured', 'Featured'), ('Limited', 'Limited')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
