# Generated by Django 5.2.7 on 2025-10-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_remove_product_isactive_remove_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='name',
        ),
    ]
