# Generated by Django 5.2.7 on 2025-10-19 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_category_img_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(choices=[('Snacks', 'Snacks'), ('Beverages', 'Beverages'), ('Stationary', 'Stationary'), ('Fishing Gear', 'Fishing Gear'), ('Cycling Gear', 'Cycling Gear'), ('Computer Accessories', 'Computer Accessories')], on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('New', 'New'), ('Sale', 'Sale'), ('Featured', 'Featured'), ('Limited', 'Limited'), ('Classic', 'Classic')], max_length=20),
        ),
    ]
